// ============================================================
// STABLE — safe to build against, won't change
// ============================================================

export type TaxonomicGroup =
  | "vascular_plant"
  | "nonvascular_plant"
  | "vertebrate"
  | "invertebrate"
  | "fungi"
  | "other";

export type OrbicRank = "S1" | "S2" | "S3" | "S4" | "S5" | "SH" | "SX";

export type FederalStatus = "LE" | "LT" | "C" | "SOC" | "none";

// ============================================================
// TBD — placeholder values until Ray's snapshot arrives.
// Update these when real column names/values are confirmed.
// ============================================================

export type EcoRegion = "BM" | "BR" | "CB" | "CR" | "EC" | "KM" | "WC" | "WV";

export type HabitatType =
  | "forest"
  | "wetland"
  | "prairie"
  | "rocky"
  | "coastal"
  | "other";

// ============================================================
// Species — the shape of one row from Ray's snapshot.
// Fields marked TBD may be renamed or removed once we see
// the actual Biotics export.
// ============================================================

export interface Species {
  // --- Identifiers (stable) ---
  slug: string;            // generated by us: "western-pond-turtle"
  commonName: string;
  scientificName: string;

  // --- Taxonomy (stable) ---
  taxonomicGroup: TaxonomicGroup;
  family?: string;         // TBD: confirm column exists in snapshot

  // --- Geography (TBD: confirm column names) ---
  ecoRegions: EcoRegion[];
  counties?: string[];
  lat?: number;            // raw — never shown directly, blurred at render time
  lng?: number;

  // --- Status (stable structure, TBD exact values) ---
  orbicRank: OrbicRank;
  federalStatus: FederalStatus;
  stateStatus?: string;    // TBD: confirm what other status fields exist
  listDate?: string;       // TBD: which version of the list this species is from

  // --- Ecology (TBD: confirm columns exist in snapshot) ---
  habitatTypes?: HabitatType[];
  isAquatic?: boolean;
  isEndemic?: boolean;     // TBD: Biotics field, not traditionally surfaced by ORBIC

  // --- Description (TBD: confirm subfields available) ---
  description?: string;
  habitat?: string;        // subfield
  threats?: string;        // subfield
  similarSpecies?: string; // subfield

  // --- Media (stable — populated from iNaturalist at build time) ---
  inatTaxonId?: number;
  photoUrl?: string;
  photoAttribution?: string;
}

// ============================================================
// QuizFilters — tracks the user's answers as they go.
// One field per quiz question. TBD fields may be removed
// if the underlying Species field doesn't exist in the snapshot.
// ============================================================

export interface QuizFilters {
  taxonomicGroup?: TaxonomicGroup;
  ecoRegion?: EcoRegion;
  habitatType?: HabitatType;  // TBD
  isAquatic?: boolean;        // TBD
  federalStatus?: FederalStatus;
}