export const filterRows = [
  {
    label: "Taxonomy",
    filters: [
      "All species",
      "Vascular Plants",
      "Nonvascular Plants and Fungi +",
      "Vertebrate Animals +",
      "Invertebrate Animals +",
    ],
  },
  {
    label: "Status",
    filters: [
      "Global Rank +",
      "State Rank +",
      "ORBIC list +",
      "Federal Status +",
      "State Status +",
      "ODFW SWAP +",
    ],
  },
  {
    label: "Geography",
    filters: ["All", "Ecoregion +", "County +", "OR Endemic"],
  },
];

export const dropdownOptions: Record<string, string[]> = {
  "Nonvascular Plants and Fungi +": [
    "Bryophtes",
    "Fungi and Lichen",
    "Kelp and Algae",
  ],
  "Vertebrate Animals +": [
    "Amphibians",
    "Birds",
    "Fishes",
    "Mammals",
    "Reptiles",
  ],
  "Invertebrate Animals +": [
    "Arthropods",
    "Molluscs",
    "Sea Stars",
    "Worms",
  ],
  "Global Rank +": [
    "G1",
    "G2",
    "G3",
    "G4",
    "G5",
    "GX",
    "GHC",
    "GHQ",
    "GNA",
    "GNR",
    "GU",
    "T1",
    "T2",
    "T3",
    "T4",
    "T5",
    "TNR",
    "TU",
    "TX",
    "Q",
    "S1",
  ],
  "State Rank +": [
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "B",
    "N",
    "SH",
    "SNR",
    "SU",
    "SX",
    "M",
  ],
  "ORBIC list +": ["1", "2", "3", "4"],
  "Federal Status +": ["E", "T", "PE", "PT", "PS", "C", "SOC", "UR", "DL"],
  "State Status +": ["C", "LE", "LT", "S", "SC"],
  "ODFW SWAP +": ["SGCN", "SGIN"],
  "Ecoregion +": [
    "Blue Mountains",
    "Northern Basin and Range",
    "Columbia Basin",
    "Coast Range",
    "East Cascades",
    "Klamath Mountains",
    "Marine and Estuarine",
    "West Cascades",
    "Willamette Valley",
  ],
  "County +": [
    "Baker",
    "Benton",
    "Clackamas",
    "Clatsop",
    "Columbia",
    "Coos",
    "Crook",
    "Curry",
    "Deschutes",
    "Douglas",
    "Gilliam",
    "Grant",
    "Harney",
    "Hood River",
    "Jackson",
    "Jefferson",
    "Josephine",
    "Klamath",
    "Lake",
    "Lane",
    "Lincoln",
    "Linn",
    "Malheur",
    "Marion",
    "Morrow",
    "Multnomah",
    "Polk",
    "Sherman",
    "Tillamook",
    "Umatilla",
    "Union",
    "Wallowa",
    "Wasco",
    "Washington",
    "Wheeler",
    "Yamhill",
  ],
};
